[platformio]
default_envs = rp2040_shim
test_dir      = tests

[env:rp2040_shim]
platform     = https://github.com/maxgerhardt/platform-raspberrypi.git
framework    = arduino
board        = silicognition_rp2040_shim
board_build.core            = earlephilhower
board_build.filesystem_size = 1m
lib_deps =
    knolleary/PubSubClient
    mobizt/ESP_SSLClient
    bblanchon/ArduinoJson
    adafruit/Adafruit NeoPixel
monitor_speed = 115200
extra_scripts = pre:scripts/gen_config.py
build_flags   =
    -DBOARD_RP2040_SHIM
    -DDEVICE_CONFIG_FILE='"devices/example.yml"'

[env:feather_rp2040]
platform     = https://github.com/maxgerhardt/platform-raspberrypi.git
framework    = arduino
board        = adafruit_feather
board_build.core            = earlephilhower
board_build.filesystem_size = 1m
lib_deps =
    knolleary/PubSubClient
    mobizt/ESP_SSLClient
    bblanchon/ArduinoJson
    adafruit/Adafruit NeoPixel
monitor_speed = 115200
extra_scripts = pre:scripts/gen_config.py
build_flags   =
    -DBOARD_FEATHER_RP2040
    -DDEVICE_CONFIG_FILE='"devices/feather-example.yml"'

[env:native]
platform = native
lib_deps =
    bblanchon/ArduinoJson
test_build_src = yes
; Exclude Arduino-hardware-dependent source files from the native build
build_src_filter =
    +<*>
    -<main.cpp>
    -<mqtt/MQTTClientWrapper.cpp>
