"""
gen_certs.py — Embed a PEM CA certificate as a C string for ESP_SSLClient (RP2040).

Reads one or more PEM certificate files and generates
src/config/trust_anchors.h containing the certificate(s) as a C string
suitable for constructing a BearSSL X509List.

Usage:
    python scripts/gen_certs.py certs/ca.crt [certs/intermediate.crt ...]

Output:
    src/config/trust_anchors.h

The generated header defines:
    const char CA_CERT_PEM[];

MQTTClientWrapper uses CA_CERT_PEM to construct an X509List for TLS verification.
If this file is absent or CA_CERT_PEM is empty, the firmware falls back to
setInsecure() (no certificate verification — development only).
"""

import os
import sys


def generate_header(pem_files, output_path):
    pem_blocks = []
    for pem_path in pem_files:
        if not os.path.exists(pem_path):
            print(f"[gen_certs] File not found: {pem_path}")
            sys.exit(1)
        with open(pem_path) as f:
            pem_blocks.append(f.read().strip())

    combined_pem = "\n".join(pem_blocks)

    # Escape for C string literal (backslash-n at line boundaries)
    escaped = combined_pem.replace("\\", "\\\\").replace('"', '\\"')
    c_lines  = '\n'.join(f'    "{line}\\n"' for line in escaped.splitlines())

    header = f"""\
// trust_anchors.h — AUTO-GENERATED by scripts/gen_certs.py
// DO NOT COMMIT private key material. Contains public CA cert(s) only.
#pragma once

static const char CA_CERT_PEM[] =
{c_lines};
"""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header)
    print(f"[gen_certs] Generated {output_path} ({len(pem_files)} cert file(s))")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)
    pem_files   = sys.argv[1:]
    output_path = os.path.join("src", "config", "trust_anchors.h")
    generate_header(pem_files, output_path)
